### PR TITLE
Ensure to exclude Emacs backup files from templates loading

### LINKED ISSUE #107: Failed to boot app if unsupported template files present
Some text editors have a habit of creating automatic backups of edited files. Emacs is among them.
The backup files (with tilde added at the end of the file name) in a view directory make hanami crash:

```
Boot Error

Something went wrong while loading /home/igneus/src/ruby/db.inadiutorium/config.ru
RuntimeError: No template engine registered for index.html.erb~

/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/loader.rb:160:in `module_eval'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/tilt-2.0.5/lib/tilt.rb:43:in `new'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/template.rb:12:in `initialize'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/templates_finder.rb:73:in `new'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/templates_finder.rb:73:in `block in find'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/templates_finder.rb:72:in `map'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/templates_finder.rb:72:in `find'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/layout_registry.rb:54:in `templates'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/registry.rb:123:in `template_for'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/registry.rb:104:in `block in prepare_views!'
/home/igneus/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/set.rb:283:in `each_key'
/home/igneus/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/set.rb:283:in `each'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/registry.rb:103:in `prepare_views!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/registry.rb:98:in `prepare!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/layout_registry.rb:24:in `initialize'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering.rb:281:in `new'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering.rb:281:in `registry'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering.rb:286:in `load_registry!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering.rb:269:in `load!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/configuration.rb:421:in `block in load!'
/home/igneus/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/set.rb:283:in `each_key'
/home/igneus/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/set.rb:283:in `each'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/configuration.rb:421:in `load!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view.rb:261:in `load!'
(eval):3:in `_load_view_framework!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/loader.rb:160:in `module_eval'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/loader.rb:160:in `_load_view_framework!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/loader.rb:154:in `load_frameworks!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/loader.rb:33:in `block in load!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/loader.rb:28:in `synchronize'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/loader.rb:28:in `load!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/application.rb:195:in `load!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/application.rb:75:in `initialize'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/container.rb:9:in `new'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/container.rb:9:in `mount'
/home/igneus/src/ruby/db.inadiutorium/config/environment.rb:8:in `block in <top (required)>'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-router-0.7.0/lib/hanami/router.rb:268:in `instance_eval'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-router-0.7.0/lib/hanami/router.rb:268:in `define'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-router-0.7.0/lib/hanami/router.rb:230:in `initialize'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/container.rb:49:in `new'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/container.rb:49:in `prepare_middleware_stack!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/container.rb:32:in `block in initialize'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/container.rb:30:in `synchronize'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/container.rb:30:in `initialize'
/home/igneus/src/ruby/db.inadiutorium/config.ru:3:in `new'
/home/igneus/src/ruby/db.inadiutorium/config.ru:3:in `block in inner_app'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
/home/igneus/src/ruby/db.inadiutorium/config.ru:1:in `new'
/home/igneus/src/ruby/db.inadiutorium/config.ru:1:in `inner_app'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/shotgun-0.9.1/lib/shotgun/loader.rb:113:in `eval'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/shotgun-0.9.1/lib/shotgun/loader.rb:113:in `inner_app'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/shotgun-0.9.1/lib/shotgun/loader.rb:103:in `assemble_app'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/shotgun-0.9.1/lib/shotgun/loader.rb:86:in `proceed_as_child'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/shotgun-0.9.1/lib/shotgun/loader.rb:31:in `call!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/shotgun-0.9.1/lib/shotgun/static.rb:14:in `call'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
/home/igneus/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/home/igneus/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/home/igneus/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

I would find it more convenient to ignore unknown files rather than crash on them.

### PR DESCRIPTION
**Pull request by jodosha**
Closes #107 

/cc @igneus

### CODE REVIEW

**Comment by maheshm** [comment]
Should we not be loading all files and raise error for ones that doesn't have an engine. I think keeping it generic would make more sense

**Comment by jodosha** [comment]
> I think keeping it generic would make more sense

What do you mean exactly? 😸 

> Should we not be loading all files and raise error for ones that doesn't have an engine.

How to discern between files to not load and files that don't have an engine?

**Comment by maheshm** [comment]
@jodosha he he.. I was talking about the suggestion by @joneslee85 in the last comment in #107

**Comment by jodosha** [comment]
@maheshm Oh I see. Thanks.

To make that possible we should suppress `RuntimeError` here https://github.com/hanami/view/blob/13faacf066d0e05a84dbb2c94ea1c8f96516b1b3/lib/hanami/view/rendering/templates_finder.rb#L73

That is the exception that Tilt raises in case an engine is missing. That sounds scary for a sensitive code spot like that one. We should also ensure a fail fast strategy for test/production environments, because we want to catch early this kind of problems.

It's not easy in both the solutions. The one proposed here requires a constant maintenance of the regexp 😢 , and the other one a special attention for edge cases.

@joneslee85 What's your idea? Thanks!

**Comment by akhramov** [comment]
@jodosha 

What about lazy initialization of Tilt templates? In this case error will be raised upon rendering. An example could be found at d688234aa64040d7330dc524c7d377cfaa8557ef.

As for fail-fast strategy... to be honest I don't know how to distinguish prod / test environments from dev one. We could emit a warning if given template is not supported.

Any thoughts?

**Comment by jodosha** [comment]
I'm closing this as the proposed solution doesn't solve the root problem. Lazy initialization of Tilt templates would require a major change in Hanami::View, which isn't worth the effort for a minor issue like this.

**Pull request closed without merging**
